### ISSUE TITLE
TypeError: 'Tree' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by alexcritschristoph** [Zsailer/pyasr#2]
Hello! When running the pyasr examples as provided, I get the following error:
```
  File "<stdin>", line 2, in <module>
  File "/home/alexcc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dendropy/datamodel/treemodel.py", line 2735, in get
    return cls._get_from(**kwargs)
  File "/home/alexcc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 155, in _get_from
    return cls.get_from_path(src=src, schema=schema, **kwargs)
  File "/home/alexcc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tree.newick'
>>> tree = d.Tree.get(path='test.newick', schema='newick')
>>> tree, df_seqs, df_anc = pyasr.reconstruct(df_seqs, tree, working_dir='test', alpha=1.235)
Traceback (most recent call last):
  File "/home/alexcc/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3124, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 55, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 63, in pandas._libs.index.get_value_box
TypeError: 'Tree' object cannot be interpreted as an integer
``

Is this code still being maintained? It seems pretty useful!
Thanks!
Alex

**Comment by Zsailer** [comment]
Oops, looks like the tutorial was out of date. I've updated the Notebook. Try out the new tutorial notebook and let me know if you are still having issues.

**Comment by alexcritschristoph** [comment]
Definitely fixed, thank you! You might want to update the code on the README page too.

**Comment by Zsailer** [comment]
@alexcritschristoph Great, thanks. I'll update the README too. 

I'd also suggest checking out and contributing to [phylogenetics](https://github.com/Zsailer/phylogenetics). This uses PyASR and PhyloPandas to take an alignment and reconstruct ancestors.

If you're interested further, checkout my talk ["Resurrecting Ancient Proteins in Python"](https://www.youtube.com/watch?v=GDt2KIWItsg) at SciPy last year.
