### ISSUE TITLE
ImporteError in phylopandas and pyasr (Bio.Alphabet has been removed from Biopython)

### ISSUE THREAD

**Issue by biomendi** [Zsailer/pyasr#4]
Hi @Zsailer 

I was trying to follow the quick tutorial under "Basic Usage". However, I get the following errors when trying to import 'phylopandas' and 'pyasr' (I made sure to have installed the corresponding python dependencies). Could this issue be fixed somehow?

`import phylopandas as pd`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/__init__.py", line 28, in <module>
    from .core import PhyloPandasDataFrameMethods as _PhyloPandasDataFrameMethods
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/core.py", line 5, in <module>
    from . import seqio
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/seqio/__init__.py", line 1, in <module>
    from .read import (read_embl,
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/seqio/read.py", line 10, in <module>
    import Bio.Alphabet
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
`import pyasr`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/pyasr/__init__.py", line 1, in <module>
    from .asr import reconstruct
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/pyasr/asr.py", line 8, in <module>
    from .read import read_codeml_output
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/pyasr/read.py", line 3, in <module>
    from phylopandas import DataFrame
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/__init__.py", line 28, in <module>
    from .core import PhyloPandasDataFrameMethods as _PhyloPandasDataFrameMethods
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/core.py", line 5, in <module>
    from . import seqio
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/seqio/__init__.py", line 1, in <module>
    from .read import (read_embl,
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/phylopandas/seqio/read.py", line 10, in <module>
    import Bio.Alphabet
  File "/home/biomendi/software/miniconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by rgsmock** [comment]
Hi, I also had the same issue. It seems pyasr had biopython==1.69. and since then Alphabet was removed from Biopython in version 1.78. This worked for me to run pyasr again without the error: 
pip install --force-reinstall biopython==1.76
